[package]
name = "kadabra"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
clap = { version = "4.5.46", features = ["derive"] }
selection = "1.2.0"
slint = "1.13.0"

[build-dependencies]
slint-build = "1.13.0"
